### PR TITLE
Compiler with Insert Get Id

### PR DESCRIPTION
**Pull request by fulviocanducci**
Return Id Inserted (int, long and guid type)

Reference https://github.com/sqlkata/querybuilder/pull/68

### CODE REVIEW

**Comment by fulviocanducci** [comment]
# Test Performed

```
MySqlCompiler mysqlCompiler = new MySqlCompiler();
PostgresCompiler npgsqlCompiler = new PostgresCompiler();
SqlServerCompiler sqlCompiler = new SqlServerCompiler();

MySqlConnection mysql = new MySqlConnection("");
NpgsqlConnection npgsql = new NpgsqlConnection("");
SqlConnection sqlconnection = new SqlConnection("");


Query q = new Query("test")
	.AsInsertGetId<int>(new string[] {"name"}, new[] {	Guid.NewGuid().ToString()});

Query q1 = new Query("test_guid")
	.AsInsertGetId<Guid>(new string[] {"name"}, new[] { Guid.NewGuid().ToString() }, "Id");

SqlResult sqlResultMysql = mysqlCompiler.Compile(q);
SqlResult sqlResultNpgsql = npgsqlCompiler.Compile(q);
SqlResult sqlResultSqlServer = sqlCompiler.Compile(q);
SqlResult sqlResultSqlServer1 = sqlCompiler.Compile(q1);


int resultMysql = mysql
    .ExecuteScalar<int>(sqlResultMysql.Sql, sqlResultMysql.Bindings);
	
int resultNpgsql = npgsql
    .ExecuteScalar<int>(sqlResultNpgsql.Sql, sqlResultNpgsql.Bindings);            
	
int resultSqlServer = sqlconnection
    .ExecuteScalar<int>(sqlResultSqlServer.Sql, sqlResultSqlServer.Bindings);

Guid resultSqlServerGuid = sqlconnection
    .ExecuteScalar<Guid>(sqlResultSqlServer1.Sql, sqlResultSqlServer1.Bindings);
```

# Output SQL

## Int or Long Type

- sqlResultMysql.Sql:  `INSERT INTO `test` (`name`) VALUES (@p0);SELECT LAST_INSERT_ID();`
- sqlResultNpgsql.Sql:  `INSERT INTO "test" ("name") VALUES (@p0) RETURNING "id"`
- sqlResultSqlServer.Sql: `INSERT INTO [test] ([name]) VALUES (@p0);SELECT SCOPE_IDENTITY();`

## Guid Type

- sqlResultSqlServer1.Sql: `INSERT INTO [test_guid] ([name]) OUTPUT INSERTED.Id VALUES (@p0)`

**Note:** _The test was also performed in the Query.Tests Project_


In creating a new "Compiler" you should implement how to retrieve the "Id" inserted in the methods: "internal override void SetConfigurationInsert ()" as follows:

### Example MySqlCompiler

```
internal override void SetConfigurationInsert()
{
	ConfigurationInsert = new Dictionary<Type, ConfigurationInsert>
	{
		[typeof(int)] = new ConfigurationInsert
		{
			LastInsertCommand = ";SELECT LAST_INSERT_ID();"
		},
		[typeof(long)] = new ConfigurationInsert
		{
			LastInsertCommand = ";SELECT LAST_INSERT_ID();"
		}
	};
}
```

### Example SqlServerCompiler

```
internal override void SetConfigurationInsert()
{
	ConfigurationInsert = new Dictionary<Type, ConfigurationInsert>
	{
		[typeof(int)] = new ConfigurationInsert
		{
			LastInsertCommand = ";SELECT SCOPE_IDENTITY();"
		},
		[typeof(long)] = new ConfigurationInsert
		{
			LastInsertCommand = ";SELECT SCOPE_IDENTITY();"
		},
		[typeof(Guid)] = new ConfigurationInsert
		{
			LastInsertCommand = " OUTPUT INSERTED.[_id_]",
			Local = " VALUES",
			InsertedCommand = true
		}
	};
}
```

### Example PostgresCompiler

```
internal override void SetConfigurationInsert()
{
	ConfigurationInsert = new Dictionary<Type, ConfigurationInsert>
	{
		[typeof(int)] = new ConfigurationInsert
		{
			LastInsertCommand = " RETURNING \"[_id_]\""
		},
		[typeof(long)] = new ConfigurationInsert
		{
			LastInsertCommand = " RETURNING \"[_id_]\""
		}
	};
}
```

And in its constructor `SetConfigurationInsert();`

```
public PostgresCompiler() : base()
{
	EngineCode = "postgres";
	SetConfigurationInsert();
}
```

**Note:** There is no way to use CompilerInsert, because it solves other issues such as "Query" and this is not necessary, so the creation of "CompileInsertGetId" which is a summary of the other

**Comment by fulviocanducci** [comment]
A question?

Do not you want to make those changes?

**Comment by ahmad-moussawi** [comment]
@fulviocanducci, actually I didn't have the time to review it before, the provided solution doesn't cover all cases, for example what happens if I call `pgsqlQuery.InsertGetId<string>()` ?
and I think the provided implementation can be improved a bit, by overriding the `CompileInsertGetId` only in the sub classes (without the configuration part), this way it will be simpler and easier to maintain, what do you think ?

**Comment by fulviocanducci** [comment]
### The provided solution doesn't cover all cases, for example what happens if I call pgsqlQuery.InsertGetId<string>() ?

There is no auto increment over text. There is only auto increment on integer, long integer and guid (SQLServer only) if one of the 3 types does not pass, we can pass an exception to the user

---

### 
and I think the provided implementation can be improved a bit, by overriding the CompileInsertGetId only in the sub classes (without the configuration part), this way it will be simpler and easier to maintain, what do you think ?

In my opinion it should have the configuration including to be worked on the part of Dapper, with this configuration I can also use in the part of running SQL

### To finish

I will not improve the code, and I will not intromenter in your package.

Thank you.

**Comment by ahmad-moussawi** [comment]
@fulviocanducci am talking here about auto generated ids in general which not necessarily auto incremented.
for example when using `gen_random_uuid` function in Postgres
```sql
CREATE TABLE users(
   id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
   name TEXT
);
insert into users(name) values('Andromeda');
```
the provided solution does not cover these cases. same goes for mysql.

anyway your contributions are always appreciated :)

**Comment by fulviocanducci** [comment]
@ahmad-moussawi 
about the code example with uuid in the "Postgres" database is the same thing just need to add this in the configuration paramenter and it is a new feature, we do not have to cover everything at once, this would be added already since Your code is a beta


Another thing:

Solution

```
CREATE TABLE users(
   id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
   name TEXT
);
insert into users(name) values('Andromeda') RETURNING "Id";
```
that is, it is the same thing that the other command has not yet been specified in the code.


In Mysql there is no UUID field, it only generates a uuid () by a function in a field 36 positions (text or char), it would not have that much trouble because in the "InsertGetId" could be done something special to mysql only for that return in configuration class.

Sorry, but, I do not agree with you said that the code does not cover everything, just configure ... as was shown in Posgres that is identical to "Serial" and "BigSerial".

Your code is a is in the "Beta" version and can be improved more and more, but, what I think you do not give space for new changes and are good for development.

If you have a code that is better, that might indicate it would be good because it somehow follows your way, but I say anti-your class Query is instantiated 2 times to generate a SQL and I see this as a big problem.

**Comment by ahmad-moussawi** [comment]
:) there is a big difference between missing features and incomplete solution, you are providing an incomplete solution that can't be merged at this phase, since it will lead to confusion for other developers who is using this library.

anyway if you need any help to assist in this please reopen it and I am ready to help.

**Comment by fulviocanducci** [comment]
@ahmad-moussawi 

I disagree

No problem, reaffirming: I do not need your help, thank you.

**Pull request closed without merging**
