### PR TITLE
Ability to add transaction when using InsertGetId

### PR DESCRIPTION
**Pull request by shiralizadeh**
Hi,
I added **Ability to add transaction when using InsertGetId**

### CODE REVIEW

**Comment by karol93** [comment]
is any chance to merge?

**Comment by shiralizadeh** [comment]
conflicts resolved.

**Comment by ahmad-moussawi** [comment]
I think I can safely close this now, since the `transactions` support is already added now by another PR.
Thanks anyway <3

**Comment by shiralizadeh** [comment]
Anytime ❤️

**Pull request closed without merging**
