### PR TITLE
sqlite compiler

### PR DESCRIPTION
**Pull request by pm100**
added sqlite support.

Afraid that I dont know the new csproj rules so not sure what else I have to update to make it compile this file (I made an old fashioned csproj for my environment)

### CODE REVIEW

**Comment by ahmad-moussawi** [comment]
Your efforts are really appreciated, but how we can make sure that this compiler will pass the current tests ?

**Comment by fulviocanducci** [comment]
Did you miss a part of the test? 


In the project: https://github.com/sqlkata/querybuilder/tree/master/QueryBuilder.Tests

**Comment by pm100** [comment]
very new to github, not sure if my test has been merged into first pull request or not

**Comment by ahmad-moussawi** [comment]
@pm100, I will close this for now, you can re submit a new request later if you prefer

**Pull request closed without merging**
