### PR TITLE
Code refactoring

### PR DESCRIPTION
**Pull request by Happi-cat**
* Renamed RawInterface into IRaw
* Dropped unused usings
* Use null coalescing in few places
* Use method directly instead of lambda where its possible
* Use pattern matching
* Style change of value wrapping code

### CODE REVIEW

**Comment by ahmad-moussawi** [comment]
@Happi-cat thanks very useful, however can you revert back the last commit 13ac0c0 for now, I know that we need a cleaner approach for the dynamic compile method, but I prefer if we open a separate issue for this and discuss what is the best approach to implement it.

**Comment by Happi-cat** [comment]
Reverted @ahmad-moussawi

**Comment by Happi-cat** [comment]
Raised an issue to keep an eye on DynamicCompile refactoring

**Comment by ahmad-moussawi** [comment]
thanks, merged now

**Pull request merged**
