### PR TITLE
PropertyInfo Caching on Update

### PR DESCRIPTION
**Pull request by rwood**
There was some talking in the Issues about this and the Dictionary had been added.  In another PR I had removed the Dictionary but felt that I should do it right and actually have the cache added.  (I did change it to Concurrent Dictionary as it's static, and we don't know if this will be run in a multi-threaded env.  In order to use the Concurrent collections, the lib has to target standard 1.1 or newer.

### CODE REVIEW

**Comment by ahmad-moussawi** [comment]
What is the advantage of using ConcurrentDictionnary instead of Dictionnary with lock, isn't the same ?

**Comment by ceastwood** [comment]
@ahmad-moussawi

I have not looked at the content of this PR but, to reply to your question:

Performance and reliability.

https://docs.microsoft.com/en-us/dotnet/standard/collections/thread-safe/when-to-use-a-thread-safe-collection

Also from elsewhere- reads from concurrentdictionary are lock free 

> ConcurrentDictionary<TKey,TValue> uses fine-grained locking when adding to or updating data in the dictionary, but it is entirely lock free for read operations.  In this way, it’s optimized for scenarios where reading from the dictionary is the most frequent operation.

**Comment by rwood** [comment]
@ceastwood, just about covered it. The only thing I can add is that I think a concurrent dictionary reads better, and there's no risk of another place in the class mutating the dictionary without respecting the lock.

**Comment by graknol** [comment]
Why hasn't this been merged into master yet? As far as I can see, this is low hanging "performance-fruit" waiting to be reaped. It's a small change, which doesn't invalidate the tests in any way. 😊

**Comment by ahmad-moussawi** [comment]
@rwood could you please resolve the conflict, so I can merge it Thanks.
@graknol thanks for the reminder

**Comment by rwood** [comment]
Wow, I really missed this one.  I'll get it resolved today.

**Comment by rwood** [comment]
@ahmad-moussawi it's updated.  Let me know if you need anything else.

**Pull request merged**
