### PR TITLE
Generic methods added.

### PR DESCRIPTION
**Pull request by senkadir**
Hi Ahmad,

I've added generic functionality to the project. 

Can you check them please?

> By the way I think there is problem with Where clauses. Results getting with sign question. '?'.
> 
>  For example when you write: `new Query("Test").Where("Id", "=", "1")`
> The result is: `SELECT * FROM Test WHERE [Id] = ?`

Thank you.

### CODE REVIEW

**Comment by ahmad-moussawi** [comment]
Thanks for the PR, I think it would be better to create a new branch for this, so we can collaborate more on it.

As a starting it's very interesting!, but can't be delivered as stable version for now.

as a quick notes:
- For multiple select I think it's better to use `Select(x => new {x.Id, x.Name})` instead of `Select(x => x.Id, x => x.Name)`
 - We should think how to handle **join** statements and some edge cases

I will review it deeply later and get back to you

**Comment by ceastwood** [comment]
+1 to @ahmad-moussawi 's comments - I will also try to take a good look at this when I can.
Also, it seems you've committed update to the .sln and .csproj, and a failed unit test.

**Comment by senkadir** [comment]
> +1 to @ahmad-moussawi 's comments - I will also try to take a good look at this when I can.
> Also, it seems you've committed update to the .sln and .csproj, and a failed unit test.

Oops! Sorry. I will handle them right now.

**Comment by senkadir** [comment]
> Thanks for the PR, I think it would be better to create a new branch for this, so we can collaborate more on it.
> 
> As a starting it's very interesting!, but can't be delivered as stable version for now.
> 
> as a quick notes:
> 
> * For multiple select I think it's better to use `Select(x => new {x.Id, x.Name})` instead of `Select(x => x.Id, x => x.Name)`
> * We should think how to handle **join** statements and some edge cases
> 
> I will review it deeply later and get back to you

Hi, Yes, branching would be better. I'll create new branch.

About your suggestions:

- `Select(x => new {x.Id, x.Name})` this is looks better. I'm agree with you.

- I'm thinking about joins.

**Pull request closed without merging**
