### PR TITLE
Allow passing in database transaction to query execution

### LINKED ISSUE #113: Transactions not being passed to dapper
I have a filter in my API that handles transactions automatically. It starts a transaction on any POST, DELETE, PUT, request. At the end of the request it commits it if no errors, otherwise rolls back.

So any of the extension methods that I use, whether it's a .Get(), .First(), or an .Insert() or .Update() it throws an error saying that a transaction is required.

### PR DESCRIPTION
**Pull request by Mitch528**
Resolves #113

### CODE REVIEW

**Comment by nauhalf** [comment]
There's still no update in SqlKata.Execution, i want to use Transaction

**Comment by nauhalf** [comment]
@RichardAnderson for now I got transaction by using TransactionScope. it's work with MySQL.

**Comment by RichardAnderson** [comment]
@nauhalf Any codesnippits on how you managed to do that, I'm working with MSSQL, but I might be able to adjust my code to accommodate it.

**Comment by nauhalf** [comment]
@RichardAnderson 

`using(var scope = new TransactionScope()){
...
//all off insert query or update or delete
...
scope.Complete();
}`

like this

**Comment by RichardAnderson** [comment]
Thanks @nauhalf 

This works perfectly for insert / update operations.  However it unfortunately does not reverse the .Statement() commands I run through QueryFactory.StatementAsync()

**Comment by lawrencetvo** [comment]
+1 Need this for my application.

**Comment by angelul** [comment]
@ceastwood any news?

**Comment by angelul** [comment]
@ahmadmuzavi Any updates? 😢

**Comment by ceastwood** [comment]
@angelul I haven't been committing to the SqlKata.Execution project but will take a deeper look this PR afternoon. At first glance I don't think the PR as-is is complete for merging, but hold my reservation.

**Comment by ceastwood** [comment]
As an update, I started to take a look and I think we might want to add the support to just a few more methods. I will circle back after work and try to update.

**Comment by ahmad-moussawi** [comment]
@angelul actually I am looking for a better way to handle transactions, I don't find that passing the transaction in all methods is the right way.

**Comment by RichardAnderson** [comment]
Hi - any update on this at all?  This is the ONLY blocker for many of my projects at present, where it's not possible to reverse all queries and statements.

**Comment by ahmad-moussawi** [comment]
@RichardAnderson why you can't use the solution suggested by @nauhalf ?
I've used this approach and it seems that it works as expected.

**Comment by myargeau** [comment]
I tried using @nauhalf's solution to get the id of the inserted (so that @@IDENTITY is executed in the same scope), but it does not work either.

**Comment by ahmad-moussawi** [comment]
@myargeau do you mind sharing code that reproduce the issue?, since I am using it with no problem with SqlServer, 
just for info, I am working on a release that tackle the transactions issue but it may need sometime to get released.

**Comment by myargeau** [comment]
This gives an error saying 'The COMMIT TRANSACTION request has no corresponding BEGIN TRANSACTION.', Like each statement is in its own context.
```
db.Statement("BEGIN TRANSACTION");

db.Query("DispatchHistory").Insert(...);
var insertedId = db.Select("SELECT @@IDENTITY");

db.Statement("COMMIT TRANSACTION");
```

This executes, but returns null (maybe because of our Trigger)
```
using (var scope = new TransactionScope())
{
	db.Query("DispatchHistory").Insert();
	var insertedIdString = db.Select("SELECT @@IDENTITY");
	scope.Complete();
}
```

This throws an exception at the first Query "ExecuteNonQuery requires the command to have a transaction when the connection assigned to the command is in a pending local transaction.  The Transaction property of the command has not been initialized." The Connection.Open() was added because the BeginTransaction() was throwing an exception saying that the connection was closed.
```
Db.Connection.Open();
using (var scope = Db.Connection.BeginTransaction())
{
    db.Query("DispatchHistory").Insert();
    var insertedIdString = db.Select("SELECT @@IDENTITY");
    scope.Commit();
}
Db.Connection.Close();
```

This works, but since I have 10 fields to insert, I lose the advantage to use SqlKata because I have to write my whole query manually.
```
var result = Db.Select<string>($@"INSERT INTO DispatchHistory (
                    Action,
                    VALUES('{actionValue}');
                    SELECT @@IDENTITY AS ID;");
```

**Comment by cunnpole** [comment]
The ability to pass in an existing transaction is vital to me as I already have a large codebase that makes heavy use of transactions. There is currently no way for me integrate Kata without using Mitch528's changes.

**Comment by kidmar** [comment]
This commit would get the work done and requires the caller to only pass the transaction in the constructor of the QueryFactory.
Also this is the way that Dapper uses for Transactions.
Why is it not getting merged?
There could be a better way to do it, but this looks like a good way and is ready...
Other proposed solutions do not work with every database

**Comment by rhaikonen** [comment]
This would be very useful to me.

**Comment by ahmad-moussawi** [comment]
starting from >= 2, all execution methods accept the transaction as a parameter.

**Pull request closed without merging**
