### PR TITLE
Declare InQuery Variables  #184

### PR DESCRIPTION
**Pull request by mota57**
@ahmad-moussawi   Please when you have a chance at your best convenience take a look at the code and and the test classes at GeneralTest.cs in order to revise it to get a better feedback.  This is the code in regards to the issue #184.

### CODE REVIEW

**Comment by ahmad-moussawi** [comment]
@mota57 thank you, but actually, the purpose of this is to benefit from the builtin engine capabilities to the max, for example, this statement
```cs
new Query("Table")
  .WithVar("@date", DateTime.UtcNow)
  .Where("Date", "@date")
```
will get translated to the following in SQL Server:

```sql
DECLARE @date DATETIME = ?
SELECT * FROM [Table] WHERE [Date] = @date;
```

the same goes for MySQL and SQLite, the only exception is Postgres since it doesn't support variable declaration in queries scope. (I don't know what the case here for Oracle)

We can expand more on this in the original issue, so it may be easier to implement.

**Comment by mota57** [comment]
Oh ok no problem I understand

**Comment by mota57** [comment]
Tengo que describir cuales son las formas en las que se puede declarar una variable en cada uno de los lenguajes


Oracle
SQLite
Firebird

**Comment by mota57** [comment]
@ahmad-moussawi  this could work with MysQL and SQLServer without problem but SQLite doesn't have the feature of declaring variables.  With Oracle you have to use "Begin" and "End". I think I need help on this one

**Pull request closed without merging**
