### PR TITLE
change Insert signature to take IReadOnlyDictionary instead of Dictionary

### PR DESCRIPTION
**Pull request by csantero**
This way I don't have to convert my `ImmutableDictionary` before calling Insert. =)

### CODE REVIEW

**Comment by ahmad-moussawi** [comment]
Thanks for your contribution :), could you give me some hint why readonly dictionary is better ? (really I don't know 😐)

**Comment by csantero** [comment]
@ahmad-moussawi this change would reduce friction when calling the Insert method if you're not using the `Dictionary` type. For example, I use `ImmutableDictionary` from System.Collections.Immutable a lot, and at present, I have to convert these to `Dictionary` in order to call Insert. Using `ConcurrentDictionary` yields the same problem. In addition to requiring more code, this conversion could potentially incur a small performance penalty as the dictionaries are copied.

`Dictionary<K,V>` already implements `IReadOnlyDictionary<K,V>`, so this change shouldn't break any existing code.

**Comment by ahmad-moussawi** [comment]
Ok Thanks for this clarifications, could you please update the **Update** method as well.

**Comment by csantero** [comment]
@ahmad-moussawi Done. I changed a usage in `Where` as well.

**Comment by ahmad-moussawi** [comment]
@csantero thanks for your contribution, PR merged

**Pull request merged**
