### PR TITLE
query execution feature, using dapper

### PR DESCRIPTION
**Pull request by ahmad-moussawi**

### CODE REVIEW

**Comment by ahmad-moussawi** [comment]
Hi @ceastwood, I am trying to push a new pull request to add the query execution feature, appveyor is failing while running the restore command, do you have any guess why this is happening ? thanks in advance

**Comment by ceastwood** [comment]
@ahmad-moussawi I will look into it this afternoon (for me), thanks

**Comment by ceastwood** [comment]
@ahmad-moussawi

Im on mobile so I havent been able to trace everything
fully but it looks like Dapper only supports .net 451 and not just net45.

Are we sure we want to integrate

**Comment by ceastwood** [comment]
@ahmad-moussawi

That was a oops, didnt mean to post and close.

Im on mobile so I havent been able to trace everything
fully but it looks like Dapper only supports .net 451 and not just net45.

Are we sure we want to integrate dapper directly in the main lib vs making a QueryBuilder.Dapper? It will add the dependency but I think there are definitely use cases where we may not want to force that dependency for everyone.

Ill check back in later today

**Comment by ahmad-moussawi** [comment]
Don't worry take your time, yes you are right, Dapper support is limited to theses frameworks, `net451;netstandard1.3;netstandard2.0`, i will try to update the target framework and try again.

For the 2nd question I think yes making this as native feature will 1) make the usage of the library way easier, 2) Most of people who search for query builder, need to execute the queries after that, 3) Currently Dapper is the defacto standard for executing queries in the dotnet world, forcing this library is like forcing the developers to use the Newtonsoft Json parser 

So forcing good behavior is recommened sometimes :)

Anyway I am open to suggestion :), and if we notice some need to a raw Query Builder we can work on it.

**Comment by ahmad-moussawi** [comment]
@ceastwood many thanks for this update 👍 , I don't think that we can make a separate library that share classes across different projects/namespaces, currently we have two options: 
1. Leave it as is, and create a new project to execute the queries, but we will sacrifice with the usability. some example would be 

```cs
var query = new Query("Users");
List<dynamic> users = queryExec.Get(query)
```

2. Adding the execution part, so it will be embedded inside the query builder, and we sacrifice with the --additional-- dependency

```cs
List<dynamic> users = factory.Query("Users").Get();
```

Or if there is a 3rd option that I've missed 

for the first two options, honestly I don't see that it deserve this separation.

**Comment by ceastwood** [comment]
@ahmad-moussawi 

Not a problem sir, and you are right about the partial classes.

I definitely see the point you are making, and I do think it's something to discuss a little. Aside from just the dependency itself, I see the execution of the queries as a completely separate concern from the creation and building of them; the project is called QueryBuilder and not QueryBuilderExecutor ;P. I think that keeping the execution bits outside of the Query class will be a good thing.

I'll just make some quick notes here for now and come back later after I finish work and have a chance to work through with some code as well.

Same project or separate projects, we can use extension methods and/or fluent interfaces to retain the syntax that you describe. I'm sure that it would be possible to keep convenience and usage as higher priorities while preserving the separation.

**Comment by csantero** [comment]
Just my 2 cents as a user: It's not a showstopper but I would prefer to consume QueryBuilder without any of the execution-related functionality. Separating the Dapper-dependent code into another NuGet pckage seems ideal.

**Comment by ahmad-moussawi** [comment]
Ok thanks guys for the feedback, I will try my best to see how I can move out this functionality on a separate project, maybe as @ceastwood mentioned, Extensions method can help here. I will share my thought with you for any news.

**Comment by ahmad-moussawi** [comment]
@ceastwood, I've created another project (Query Execution) to handle the execution part of the query using Dapper, so as discussed before, now we have two different projects (as per your opinion), my question is, is it possible to automate the package creation for the two projects using appveyor ?

**Comment by ceastwood** [comment]
@ahmad-moussawi 

It is, but I would like to do some cleanup of your PR first. I think we should change the naming of the project to SqlKata.Execution or SqlKata.Dapper (since is is tied directly to dapper) so they will match the nuget package name(s). I'll look over the changes later this evening when I can

Thanks

**Comment by ceastwood** [comment]
@ahmad-moussawi 

I'm closing this, and creating an issue for us to discuss on.

**Pull request closed without merging**
