### PR TITLE
Genericss added

### PR DESCRIPTION
**Pull request by senkadir**
Hi All,

I've added generics with joins. Please take a look.

### CODE REVIEW

**Comment by senkadir** [comment]
Guys, AppVeyor CI show error on OracleLegacyLimitTest. This error comes to me with my last get.

**Comment by for7raid** [comment]
Hi guys!
I'm not sure that is good idea to make another ORM over the sqlkata. It may be seems simple task, but in fact this is very hard work to make really good fully working ORM with all needed operations.

Talking about the commit exactly, I think that is bad solution about join

`        public void InnerJoinTest()
        {
            var q = new Query<Entity>().Join<JoinEntity>((x, y) => x.Id == y.EntityId);
       ...
            var expected = $"SELECT * FROM [Entity] \nINNER JOIN [JoinEntity] ON [Id] = [EntityId]";
       ...
        }
`
In real word we use primary key name is table name + id, not only id, so, expected should be

`  var expected = $"SELECT * FROM [Entity] \nINNER JOIN [JoinEntity] ON [Entity].[EntityId] =  [JoinEntity].[EntityId]";`

i.e. with full table name or alias and column name.
The same touches where, order. having and other - when you join tables, you have to use full qualified column name.

In Order expression it is not enough to say only column names, i need a direction. Does is work .OrderBy(new {x.Column}).OrderByDesc(new {x.Column2})  properly? In LINQ i use OrderBy and ThenBy methods.

What about As statement for column names? MySQL and Postgree is case sensitive, table and column names usually in lower case, and you have to make all names lower, but the Dapper, I suppose, expects the columns in the same case, as you provide in expression.

Another warning - no caching, It is long operation to parse expression every time, productivity will very low to use it in production.

I think it is better to use something like NHibernate or EntityFramework when you want to work with strong typed domain drive solution.

**Comment by senkadir** [comment]
Hi for7raid,

Tablename+id notation will be available with my next commit. I realized that notation is necessity but I am busy at my work.

Of course you can use ORM tool but I just try to create sql texts with strongly types. This was just idea it doesn't have to be.

**Comment by ahmad-moussawi** [comment]
@senkadir thanks for your feedback, currently there is no plan to release this, we are just experimenting, and the idea is promising but I think it's not complete yet.
Yes SqlKata is not made to replace ORMs, and will not be like this.

**Pull request closed without merging**
