### PR TITLE
Avoid parameter sniffing for exists subquery

### PR DESCRIPTION
**Pull request by yoosoopov**
parameterized  top (@p0) in subquery leeds to performance issue

### CODE REVIEW

**Comment by ahmad-moussawi** [comment]
Do you have any reference/benchmarks for that?

**Comment by yoosoopov** [comment]
> Do you have any reference/benchmarks for that?

image

I have a 1:N relationship table, parameterized exists subquery leeds to full scan of referenced table

**Comment by ahmad-moussawi** [comment]
I appreciate if you can post some reproducible code

**Comment by yoosoopov** [comment]
> I appreciate if you can post some reproducible code

```
/*

-- create table a
select a.[object_id], a.[name] into a from sys.objects as a, sys.objects as b

-- create table b
select a.[object_id] into b from sys.objects as a

-- create indexes 
create index ix_a_0 on a([object_id])
create index ix_b_0 on b([object_id])

*/

set statistics io on

declare @top as int

set @top = 1

select top 100 * from a where 
    exists (select top (1) 1 from b where b.[object_id] = 4 and a.[object_id] = b.[object_id])

select top 100 * from a where 
   exists (select top (@top) 1 from b where b.[object_id] = 4 and a.[object_id] = b.[object_id])

```


(0 rows affected)
Table 'Worktable'. Scan count 0, logical reads 0, physical reads 0, read-ahead reads 0, lob logical reads 0, lob physical reads 0, lob read-ahead reads 0.
Table 'a'. Scan count 1, logical reads 3, physical reads 0, read-ahead reads 0, lob logical reads 0, lob physical reads 0, lob read-ahead reads 0.

(0 rows affected)
Table 'b'. Scan count 2972176, logical reads 5954696, physical reads 0, read-ahead reads 0, lob logical reads 0, lob physical reads 0, lob read-ahead reads 0.
Table 'a'. Scan count 1, logical reads 30564, physical reads 0, read-ahead reads 0, lob logical reads 0, lob physical reads 0, lob read-ahead reads 0.

**Comment by yoosoopov** [comment]
` select 1 ` is equal to ` select top(1) 1 ` in performance

**Comment by ahmad-moussawi** [comment]
Thanks a lot

**Comment by regme** [comment]
Seems like there is some problem with CI build for NuGet? 😭 
How can we get an updated package?

**Comment by ahmad-moussawi** [comment]
@regme it seems the build is ok, and the NuGet packages are published as excepted, are you still facing this issue?

**Comment by regme** [comment]
> @regme it seems the build is ok, and the NuGet packages are published as excepted, are you still facing this issue?

I was expecting to find an updated version of the NuGet package with changes from PR #309 
But the latest available version of the package is **1.1.8-ci-712**  built on Wed, 07 Aug 2019

**Comment by ahmad-moussawi** [comment]
Nightly build packages are hosted on MyGet, https://www.myget.org/feed/sqlkata/package/nuget/SqlKata.Execution/1.1.8-0-717

**Pull request merged**
