### PR TITLE
Provide interfaces for IQuery, IBaseQuery<Q>, IXQuery and IQueryFactory

### PR DESCRIPTION
**Pull request by fschick**
I am using (and extending) querybuilder in a project that uses dependency injection. Within the unit tests I came accross the fact that querybuilder isn't using any interfaces. This makes mocking of queries nearly impossible. For this reason, I added interfaces. I know, it's a bigger change and not necessary for some people.

Example for (now possible) mocking:

	using (var fake = new AutoFake())
	{
		var expectedResult = new Query { Method = "TestMethod" };

		var query = fake.Resolve<IQuery>();
		A.CallTo(() => query.Where(null, null)).WithAnyArguments().Returns(expectedResult);
		                     => this is not possible without interface (or virtual members).

		var result = query.Where("Id", "1");
		Assert.Equal(expectedResult.Method, result.Method);
	}

To get it work, I had to change 

`AbstractQuery.EngineScope` from field to property
`Query.GetOffset` made public
`Query.GetLimit` made public
`QueryFactory.Logger` from field to property
`XQuery.Logger` from field to property

in addition to add interfaces.

### CODE REVIEW

**Comment by ahmad-moussawi** [comment]
If am not wrong, the docs state that classes with public constructors can be faked as well, isn't this the case ?
https://fakeiteasy.readthedocs.io/en/stable/what-can-be-faked/

**Comment by fschick** [comment]
The class itself can be faked. But no method calls can be intercepted. Example

	var query = fake.Resolve<Query>();
	                         => Using the class, not the interface.
	A.CallTo(() => query.Where(null, null)).WithAnyArguments().Returns(expectedResult);
	                     => Member Where can not be intercepted. 
	                        Only interface members and virtual, 
	                        overriding, and abstract members can be intercepted.

Antoher approach could be to make all memebers virtual. But's the reason is not immediately apparent. Interfaces seems to be the more cleaner solution for me.

Of course, there are other ways to encapsulate the tests, e.g. encapsulate SqlKata into a separate service with interfaces and mock it afterwards. It would only be nice to have this out of the box.

**Comment by ahmad-moussawi** [comment]
OK thanks for the info, currently providing interfaces will make dealing with this library more harder, in terms of maintenance and usage, since there is no clear reason to use it.

I prefer if we follow other approaches for the moment.

**Comment by fschick** [comment]
Providing interfaces is always a good idea, not only for DI. But I agree with you it makes things initially more complex, especially for smaller solutions. You can close the request, if you don't want to merge.

**Comment by ahmad-moussawi** [comment]
Agree with you, but actually there is a plan for a major rewrite of the query builder in 2.0 to add more features, stick with interfaces at this phase will limit the flexibility, maybe I will reconsider this later. Thanks for your effort anyway

**Pull request closed without merging**
