### PR TITLE
allow select without table to support cross apply

### PR DESCRIPTION
**Pull request by mnsrulz**
This PR is addressing some of the issues reported earlier #123 #104 

where people want to select some static values or native database functions or to support column reusability of cross/outer apply. The majority of the database provider supports this.

Let me know your thoughts on this one.

### CODE REVIEW

**Comment by mnsrulz** [comment]
@ahmad-moussawi would you consider reviewing this and let me know what's your thoughts on this?

**Comment by ahmad-moussawi** [comment]
@mnsrulz I agree with you regarding omitting the no-table exception.
But I don't want to add an explicit `CrossApply` since it's the same as `LATERAL JOIN` in MySql for example,
So I prefer keeping it as an optional parameter where the developer can pass the join type there.

**Comment by mnsrulz** [comment]
Gotcha! I can remove those explicit cross apply and outer apply methods.

**Comment by mnsrulz** [comment]
> @mnsrulz I agree with you regarding omitting the no-table exception. But I don't want to add an explicit `CrossApply` since it's the same as `LATERAL JOIN` in MySql for example, So I prefer keeping it as an optional parameter where the developer can pass the join type there.

@ahmad-moussawi  the pr has been updated. sorry for the late fix.

**Comment by ahmad-moussawi** [comment]
@mnsrulz the PR is merged now, thanks

**Pull request merged**
