### PR TITLE
Fix places where the parameterPlaceholder is hardcoded to a ? 

### PR DESCRIPTION
**Pull request by toburger**
Accidentally closed the old PR #592

### CODE REVIEW

**Comment by ahmad-moussawi** [comment]
Merged now thanks!

**Comment by toburger** [comment]
When do you plan to release a new NuGet package?

**Comment by kamisoft-fr** [comment]
Hi guys, I tested the new code and unfortunately we still have a last hardcoded question mark in **SqlResult**


```public override string ToString()
        {
            var deepParameters = Helper.Flatten(Bindings).ToList();

            return Helper.ReplaceAll(RawSql, "?", i =>
            {
                if (i >= deepParameters.Count)
                {
                    throw new Exception(
                        $"Failed to retrieve a binding at index {i}, the total bindings count is {Bindings.Count}");
                }

                var value = deepParameters[i];
                return ChangeToSqlValue(value);
            });
        }

```
Apparently the compiler is not saved in any of the properties or fields of **SqlResult**, otherwise I would have created a PR :)

**Comment by ahmad-moussawi** [comment]
@kamisoft-fr thanks for reporting, oops yes this still missing, we should find a way to instruct the `SqlResult` to copy the placeholder from the compiler, do you have any suggestion?

**Comment by flookami** [comment]
Hi @ahmad-moussawi, do you have the time to take a look at PR https://github.com/sqlkata/querybuilder/pull/592 ?
it's been months I've made the pull request in order to change the default parameter placeholder & use JSON queries in my code base :)

**Pull request merged**
