### PR TITLE
Fix places where the `parameterPlaceholder` is hardcoded to a `?`

### PR DESCRIPTION
**Pull request by toburger**
There are places where the `parameterPlaceholder` variable isn't used and the `?` (question mark) is hardcoded in code.

This prevents the redefinition of the `parameterPlaceholder` to another value.

#### Practical usage:

It is not possible to define JSON (Postgres) specific queries because some of the keywords use the question mark.

Example:

```c#
query.WhereRaw(@$"data->>'Tagging'::jsonb @? '$.{tagkey}\[*\] ? (@.Id == ""{tag}"")'")
```

The `?` gets interpreted as a parameter and throws an exception.

With the changes in place the `parameterPlaceholder` can be redefined to use another value, for example the `$$` value can be used insetad by inheriting a new class from e.g. PostgresCompiler:

```c#
class MyPostgresCompiler : PostgresCompiler
{
    public MyPostgresCompiler()
    {
        parameterPlaceholder = "$$";
    }
}
```

Now the query works as expected after all desired occurrences of `?` are replaced with `$$` in your code.

### CODE REVIEW

**Comment by kamisoft-fr** [comment]
Same problem here :)
@ahmad-moussawi , can you take a look at it ? 
thanks

**Comment by ahmad-moussawi** [comment]
@toburger I see that there is still some reference of the `?` still hardcoded, in the Firebird and SQLiteCompiler, 
https://github.com/sqlkata/querybuilder/commit/2e58816329162689746d792af76c76f35b028a90
can you push an update to address those?
or alternatively give me the permission to modify this PR https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork

**Comment by toburger** [comment]
Sorry, don't know what happened. It has closed the PR automatically.
I've made a new PR here with your changes applied: #616

**Comment by kamisoft-fr** [comment]
Hi, just created the PR #628 for the SqlResult class still containing the question mark hardcoded
I know that I made a breaking change on the class, but I did't found another way for the moment...

**Pull request closed without merging**
