### PR TITLE
Delete with joins

### PR DESCRIPTION
**Pull request by mathijs-dumon**
Pull request to rebase this old branch onto master

Related to #182

### CODE REVIEW

**Comment by ahmad-moussawi** [comment]
I think this branch needs rebasing with master

**Comment by mathijs-dumon** [comment]
Yes that's what I did in my forked repository

**Comment by mathijs-dumon** [comment]
hm seems something isn't quite ok, I'll redo the rebase later

**Comment by Dave-Coll** [comment]
Has this been completed and added yet or still outstanding? I see the branch is still active and don't see it mentioned in release notes for 2.3.8

**Comment by ahmad-moussawi** [comment]
I will close this one, since the same functionality is merged here #614 
@Dave-Coll this is merged now, will be available in the next release, or you can use the Github Prerelease Feed

**Pull request closed without merging**
