### PR TITLE
Replace Inflector.cs

### PR DESCRIPTION
**Pull request by Svetomechc**
Replaces Inflector.cs with a slightly better alternative.

### CODE REVIEW

**Comment by ahmad-moussawi** [comment]
@Svetomechc  thanks for this enhancement, but do you know why the build is failing ?

**Comment by Svetomechc** [comment]
Currently have no idea, since the following command...

> dotnet msbuild /t:Build /p:Configuration=Release /nologo

...executes on my machine just fine.

**Comment by Svetomechc** [comment]
Can you rerun the build?

**Comment by Svetomechc** [comment]
Seems to be working correctly now.

**Pull request merged**
