### PR TITLE
Adds ability to escape identifiers w/ tests

### PR DESCRIPTION
**Pull request by joshcobalt**
Here is a commit to allow for escaping identifiers #215

### CODE REVIEW

**Comment by joshcobalt** [comment]
It's not looking for the paren, it's just part of the matching group.

"Zero-width negative lookbehind. Look behind the current position to determine whether subexpression does not match the input string."
https://docs.microsoft.com/en-us/dotnet/standard/base-types/best-practices#take-charge-of-backtracking

I'd also like to apply the escape behavior to the Compiler.WrapValue() method, but I'm trying to determine a clean way of accomplishing that -- any ideas?

**Comment by joshcobalt** [comment]
The reason for escaping in WrapValue() is so I can control the raw SQL in the SELECT statements as well.

**Comment by joshcobalt** [comment]
I added some more tests and tweaked the regex, I feel like this is now complete.

**Comment by ahmad-moussawi** [comment]
Merged with the master branch, thanks!

**Pull request merged**
