### PR TITLE
AppVeyor / Build Enhancement

### PR DESCRIPTION
**Pull request by ceastwood**
[Issue #25](https://github.com/sqlkata/querybuilder/issues/25)

I removed the reference to example.csproj since you have example in .gitignore it caused problems with the CI-builds.

### CODE REVIEW

**Comment by ahmad-moussawi** [comment]
Thanks for your effort!, does this pr allows automatic nuget publishing ?

**Comment by ceastwood** [comment]
The AppVeyor config file is configured to push to nuget after a successful build / commit on the master branch, I would just make sure that you have the correct apikey saved under the deploy section; so yes, I believe so.

**Comment by ceastwood** [comment]
After we confirm this PR, I would say that it may be a good idea to change the setup a little bit;

CI / commit builds on master publish to myget
Tagged commits on master publish to nuget

So that only intentional builds get pushed to nuget for most people to go and download.

**Comment by ahmad-moussawi** [comment]
@ceastwood PR accepted, your efforts are really appreciated

**Comment by ceastwood** [comment]
@ahmad-moussawi 

I haven't asked but it looks like you may have setup MyGet using their build services integration? If so let me know, we would likely want to have AppVeyor do the integration instead of that method.

I also wanted to see what your thoughts were on separating commits to master from the NuGet releases as there are several ways to get there. Don't want to push half-baked changes public by accident :) We can get these changes in on this PR since you haven't merged yet.

The easiest to setup might be that we just make it so commits to master will build and push to MyGet. Then once a set of changes are ready for a full publish, a tagged commit to master it will upload to NuGet. I'd also recommend creating a 'dev' branch and all work gets committed there until you are ready to push a group of changes (then merging to master). Let me know what you were thinking so that I can help out with the configs and everything.

Thanks ;D

**Comment by ahmad-moussawi** [comment]
@ceastwood Yes I've used to MyGet before, but I didn't complete it, so if you feel thats would add a value, go ahead, 

Regarding the separate commits its seems also a good idea !

What do you need from my end to make such setup ?

**Comment by ceastwood** [comment]
@ahmad-moussawi 

I believe using AppVeyor to push the packages to MyGet would add value, yes. Among other things, it means that the build script in this repo controls the build / package creation / test /versioning rather than having two or more different setups to monitor.

For the other changes I've described there are two ways we can go about it so that would be up to you. 

I could describe the changes to make in different places for you as it's not very much work or we could work out giving me access to the repo/myget/AppVeyor so that I can make the changes and test them to make sure everything works as planned as well as potentially helping out moving forward. Either would work for me.

Let me know, you can also send me an email if you wanted to discuss.

**Comment by ahmad-moussawi** [comment]
@ceastwood I've sent you invitations on MyGet, AppVeyor and Github, so we will go with what you have suggested regarding the package publishing strategy (y)

**Pull request merged**
